%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace.

% Auto-generated by MATLAB (R2025b) and Database Toolbox Version 25.2 on 26-Apr-2026 16:26:32
function [resultado] =  consultaDato ()
%% Make connection to database
conn = database('productos');

%Set query to execute on the database
query = ['SELECT ID_PRODUCTO_50, CANTIDAD_50, PRECIO_COSTO_50, PRECIO_UNITARIO_50 ' ...
    'FROM productos_50 WHERE ESTADO_50=1 ORDER BY ID_PRODUCTO_50 DESC'];

%% Execute query and fetch results
data = fetch(conn,query);

%% Close connection to database
close(conn)

%% Clear variables
clear conn query

if isstruct (data)
    resultado = struct2table(data);
elseif iscell(data)
    resultado = cellt2table(data);
else 
    resultado = data;
end